name: ci

on:
  push:
    branches: [ main, master, gpt5 ]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tooling
        run: |
          uv venv
          uv pip install ruff black isort mypy pytest pytest-asyncio
      - name: Lint & type check
        run: |
          uv run ruff check .
          uv run ruff format --check .
          uv run black --check .
          uv run isort --check-only .
          uv run mypy src
      - name: Tests
        run: |
          uv run pytest -q
