name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup uv
        uses: astral-sh/setup-uv@v4

      - name: Install deps
        run: |
          uv sync --dev

      - name: Lint (ruff)
        run: |
          uv run ruff check .

      - name: Format check (ruff/black/isort)
        run: |
          uv run ruff format --check .
          uv run black --check .
          uv run isort --check-only .

      - name: Type check (mypy)
        run: |
          uv run mypy

      - name: Tests (pytest)
        run: |
          uv run pytest -q
